name: kiosk
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  #state
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  
  #service
  connectivity_plus: ^6.1.5
  easy_localization: ^3.0.3
  pdfx: ^2.7.0
  path_provider: ^2.1.4
  device_info_plus: ^12.2.0
  package_info_plus: ^8.1.0
  uuid: ^4.5.1

  #cache
  # shared_preferences: ^2.5.3

  # debug
  logger: ^2.5.0
  
  #design
  timelines_plus: ^1.0.7
  lottie: ^3.3.2
  animated_flip_counter: ^0.3.4
  simple_animations: ^3.0.2
  iconify_flutter: ^0.0.7
  hugeicons: ^1.1.1
  cached_network_image: ^3.4.1
  signature: ^5.5.0

  # analysis
  mixpanel_flutter: ^2.4.4
  sentry_flutter: ^9.6.0
  feedback: ^3.2.0

  #security
  flutter_dotenv: ^6.0.0

  # http
  dio: ^5.9.0
  # http: ^1.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/lang/
    - assets/gif/
    - assets/images/
